<a href="https://colab.research.google.com/github/raju1207/Zomato_Restaurants_Dataset/blob/main/Zomato_restaurants_dataset_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('zomato.csv')

In [3]:
data

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...,...,...
7100,7100,7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,7101,7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,7102,7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7105 entries, 0 to 7104
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           7105 non-null   int64
 1   Unnamed: 0             7105 non-null   int64
 2   restaurant name        7105 non-null   object
 3   restaurant type        7105 non-null   object
 4   rate (out of 5)        7037 non-null   float64
 5   num of ratings         7105 non-null   int64
 6   avg cost (two people)  7048 non-null   float64
 7   online_order           7105 non-null   object
 8   table booking          7105 non-null   object
 9   cuisines type          7105 non-null   object
 10  area                   7105 non-null   object
 11  local address          7105 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 666.2+ KB

In [ ]:
# 1. What is the average rating of restaurants for each type (e.g., Quick Bites, Cafe)?

In [6]:
# Average rating by restaurant type
average_rating = data.groupby('restaurant type')['rate (out of 5)'].mean()
print(average_rating)

restaurant type
Bakery                     3.480537
Bakery, Beverage Shop      3.200000
Bakery, Cafe               3.814286
Bakery, Dessert Parlor     3.613333
Bakery, Quick Bites        3.420000
                             ...
Quick Bites, Sweet Shop    3.550000
Sweet Shop                 3.473913
Sweet Shop, Quick Bites    3.454839
Takeaway                   3.322222
Takeaway, Delivery         3.289161
Name: rate (out of 5), Length: 81, dtype: float64

In [ ]:
# 2. Which area has the highest number of restaurants listed?

In [7]:
# Count of restaurants by area
restaurant_count = data['area'].value_counts()
print(restaurant_count)

area
Byresandra,Tavarekere,Madiwala    798
Bannerghatta Road                 552
Brookefield                       477
Brigade Road                      464
Indiranagar                       455
Electronic City                   403
Malleshwaram                      402
Kalyan Nagar                      384
Bellandur                         361
Banashankari                      359
Whitefield                        261
Marathahalli                      260
HSR                               241
Basavanagudi                      214
New BEL Road                      168
Koramangala 4th Block             162
Rajajinagar                       148
Lavelle Road                      141
Jayanagar                         127
Frazer Town                       126
Sarjapur Road                     108
Old Airport Road                   91
Church Street                      77
Koramangala 6th Block              71
JP Nagar                           69
Kammanahalli                       65
Koramangala 7th Block              36
Koramangala 5th Block              35
MG Road                            32
Residency Road                     18
Name: count, dtype: int64

In [ ]:
# 3. What is the average cost for two people in restaurants that offer online ordering vs. those that don't?

In [9]:
# Average cost comparison by online order availability
average_cost_online = data.groupby('online_order')['avg cost (two people)'].mean()
print(average_cost_online)

online_order
No     598.925023
Yes    488.035686
Name: avg cost (two people), dtype: float64

In [ ]:
# 4. Which restaurant(s) have the maximum number of ratings?

In [10]:
# Restaurant(s) with the highest number of ratings
max_ratings = data['num of ratings'].max()
top_rated_restaurants = data[data['num of ratings'] == max_ratings]
print(top_rated_restaurants[['restaurant name', 'num of ratings']])

                  restaurant name  num of ratings
1035  Byg Brewski Brewing Company           16345

In [ ]:
# 5. What are the top 5 cuisines served most frequently in the dataset?

In [12]:
# Top 5 most common cuisines
from collections import Counter

# Split cuisines and count frequency
cuisines_list = data['cuisines type'].str.split(',').sum()
top_cuisines = Counter(cuisines_list).most_common(5)
print(top_cuisines)

[(' Chinese', 1983), ('North Indian', 1943), (' North Indian', 1294), ('South Indian', 841), (' Fast Food', 642)]